name: hun_nest_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.8
  built_value: 8.9.5
  built_collection: 5.1.1
  wc_form_validators: 1.1.0
  cached_network_image: 3.4.1
  dio: 5.8.0+1
  bloc: 9.0.0
  flutter_bloc: 9.1.1
  hydrated_bloc: 10.0.0
  flutter_dotenv: 5.2.1
  path_provider: 2.1.5
  path: 1.9.1
  flutter_svg: 2.1.0
  image_picker: 1.1.2
  wc_dart_framework: 1.9.1
  google_fonts: 6.2.1
  file_picker: 10.1.2
  intl: 0.19.0
  public_internal_annotation: 3.0.0
  url_launcher: 6.3.1
  go_router: 15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.4.15
  built_value_generator: 8.9.5
  wc_dart_framework_generator: 1.9.4
  public_internal: 3.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/svgs/
    - assets/images/others/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
